<?php

/**
 * ProcessWire Table CSV Export Helper
 * by Adrian Jones
 *
 * Helper process module for generating CSV from a Table field
 *
 * ProcessWire 2.x
 * Copyright (C) 2011 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class ProcessTableCsvExport extends Process implements Module {

    /**
     * getModuleInfo is a module required by all modules to tell ProcessWire about them
     *
     * @return array
     *
     */
    public static function getModuleInfo() {
        return array(
            'title' => __('Process Table CSV Export'),
            'version' => '1.0.3',
            'summary' => __('Helper module for creating CSV to export'),
            'author' => 'Adrian Jones',
            'href' => 'http://modules.processwire.com/modules/table-csv-import-export/',
            'singular' => true,
            'autoload' => false,
            'page' => array(
                'name' => 'table-csv-export',
                'parent' => 'setup',
                'title' => 'Table CSV Export',
                'status' => 'hidden'
            ),
            'permission' => 'table-csv-export',
            'permissions' => array(
                'table-csv-export' => 'Access to Table CSV Export'
            ),
            'requires' => 'TableCsvImportExport',
            );
    }


    /**
     * Initialize the module
     *
     */
    public function init() {
        parent::init();
        $this->wire()->addHook('Page::exportTableCsv', $this, 'exportCsv'); // not limited to table-csv-export permission because only relevant to front-end
    }

    /**
     * Executed when root url for module is accessed
     *
     */
    public function ___execute() {
        $this->exportCsv();
    }


    public function outputCSV($data, $delimiter, $enclosure) {
        $output = fopen("php://output", "w");
        foreach ($data as $row) {
            fputcsv($output, $row, $delimiter == "tab" ? chr(9) : $delimiter, $enclosure);
        }
        fclose($output);
    }


    public function exportCsv($event = NULL) {
        $fieldName = $this->wire('input')->get->fn;
        $delimiter = $this->wire('fields')->get($fieldName)->delimiter;
        $enclosure = $this->wire('fields')->get($fieldName)->enclosure;
        $extension = $this->wire('fields')->get($fieldName)->extension;
        $exportTemplate = $this->wire('fields')->get($fieldName)->template;


        $csv = array();

        //actual field name is never mangled with a repeater extension
        $actualFieldName = (strpos($fieldName, '_repeater') !== FALSE) ? strstr($fieldName, '_repeater', true) : $fieldName;

        //get actual page, considering it might be a repeater
        if($actualFieldName != $fieldName) $repeaterId = str_replace($actualFieldName . '_repeater', '', $fieldName);
//        if(isset($repeaterId)) {
//            $page = $this->wire('pages')->get($repeaterId);
//        }
//        else {
            $page = !is_null($event) ? $event->object : $this->wire('pages')->get((int)$this->wire('input')->get->pid);
//        }

        $page->of(false);
        $thisTable = $page->$fieldName; // get table field from current page

        if (sizeof($thisTable) == 0){
            $thisTable->getNew();
        }
        if (sizeof($thisTable) == 1){
            $thisTable->getNew();
        }
        $thisExportTable = $page->$exportTemplate;
        if ($thisExportTable->first()->fields == null){
            $thisExportTable->getNew();
        }
        $thisExportTableField = $thisExportTable->first()->fields;

        $fields = array();

        foreach ($thisExportTableField as $field){
            $fields[] = $field;
        }


        $column = 0;
        foreach($fields as $field){
            $csv[0][$column] = $field;
            $column++;
        }

        $row = 1;
        foreach($thisTable as $tableItem){
            $wholeRowEmpty = true;
            foreach($fields as $field) {
                barDump($tableItem->$field);
                if ($tableItem->$field != "") {
                    $wholeRowEmpty = false;
                }
            }
            if ($wholeRowEmpty == false) {
                foreach ($fields as $field) {
                    barDump($tableItem->$field);
                    if (isset($tableItem->$field)) {
                        if ($tableItem->$field != "") {
                            $csv[$row][$column] = $tableItem->$field;
                        } else {
                            $csv[$row][$column] = "";
                        }
                    } else {
                        $csv[$row][$column] = "";
                    }
                    $column++;
                }
            }
            $row++;
        }

        header("Content-type: text/csv");
        header("Content-Disposition: attachment; filename=".$fieldName . "_" .$page->title . ".".$extension);
        header("Pragma: no-cache");
        header("Expires: 0");

        $this->outputCSV($csv, $delimiter, $enclosure);
        exit;
    }
}
